Improving logger (#28)
* chore: improve pre commit hook

* style: improve health check router name at main

* docs: update readme

* refactor: move go funk to direct dependencies

diff --git a/tools/hooks/pre-commit b/tools/hooks/pre-commit
--- a/tools/hooks/pre-commit
+++ b/tools/hooks/pre-commit
@@ -32,22 +32,23 @@ do
   printf "\033[1;33m"
   $GOLINT $FILE | egrep -v -w "should have comment|lint suggestions; failing"
   printf "\033[0m"
-
-  # Run govet on the staged file and check the exit status
-  go vet $FILE
-  if [[ $? != 0 ]]; then
-    printf "\t\033[31mgo vet $FILE\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
-    PASS=false
-  else
-    printf "\t\033[32mgo vet $FILE\033[0m \033[0;30m\033[42mpass\033[0m\n"
-  fi
 done
 
+# Run go vet for all project files
+go vet $(go list ./... | grep -v /vendor/)
+if [[ $? != 0 ]]; then
+  printf "\t\033[0;30m\033[41mgo vet fails\033[0m\n"
+  PASS=false
+else
+  printf "\t\033[0;30m\033[42mgo vet pass\033[0m\n"
+fi
+
+
 if ! $PASS; then
-  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
+  printf "\033[0;30m\033[41mSome checks has failed, aborting commit\033[0m\n"
   exit 1
 else
-  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
+  printf "\033[0;30m\033[42mAll checks has passed\033[0m\n"
 fi
 
 exit 0
